### ISSUE TITLE
Can't load timezone with JQuery.

### ISSUE THREAD

**Issue by codefuze** [mde/timezone-js#50]
I am trying to get this to work with JQuery. I get the following error:

```
Uncaught Error: Timezone "America/Chicago" is either incorrect, or not loaded in the timezone registry.
```

The readme states I would need too create a custom transport method. Could anyone give an example on how I would do this or create a wiki for it. Sorry to create an issue, this has been driving me crazy!

**Comment by lucasboko** [comment]
Hi all, 

I keep getting this in my console while using timezone.js :

warning : Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.

error: GET http://exodo/tz/asia 404 (Not Found)

error : Uncaught TypeError: Cannot read property '1' of null

// code snipet
timezoneJS.timezone.zoneFileBasePath = 'tz';
                timezoneJS.timezone.defaultZoneFile = ['asia', 'backward', 'northamerica', 'southamerica'];
                timezoneJS.timezone.init({ async: false });
                var dt = new window.timezoneJS.Date(new Date());
                console.debug(dt.toString());
                dt.setTimezone('America/Los_Angeles');
                alert(dt);

**Comment by lucasboko** [comment]
Just found the solution. The list of Olson files where missing in /tz folder.
